apiVersion: v1
kind: Pod
metadata:
  name: nginx-phpfpm
  labels:
    app: php-app
spec:
  volumes:
    - name: nginx-config-volume
      configMap:
        name: nginx-config
    - name: shared-files
      emptyDir: {}
  containers:
    - name: php-fpm-container
      image: php:7.2-fpm-alpine
      volumeMounts:
        - name: shared-files
          mountPath: /var/www/html
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 8099
      volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: shared-files
          mountPath: /var/www/html
